config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs
  resources :owners
  resources :shelters
  resources :owner_sessions, only: [:new, :create, :destroy]
  resources :shelter_sessions, only: [:new, :create, :destroy]
  resource :adoptions, only: [:new, :create]

  get '/move', to: 'adoptions#move'
  get '/old-dogs', to: 'dogs#oldDogs'

  get '/auth/facebook/callback' => 'owner_sessions#create'
  root to: 'static#index'
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_secure_password

  validates :name, :password_digest, presence: true, on: :create
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }, on: :create
  validates :email, presence: true, on: :update
  validates :about_us, :home_state, presence: true, allow_blank: true

  has_many :dogs
  has_many :adoptions
  has_many :owners, through: :adoptions
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  include ApplicationHelper
  include SheltersHelper
  include OwnersHelper


  def new
    @shelter = Shelter.new()
  end

  def create
    if session[:shelter_id].nil? && session[:shelter_id].nil?
      @shelter = Shelter.new(shelter_params)
      if @shelter.valid?
        @shelter.save
        redirect_to new_shelter_session_path
      else
        render :new
      end
    else
      redirect_to dogs_path, alert: 'You must sign out before creating a new account.'
    end
  end

  def show
    if validate_shelter()
      @shelter = Shelter.find_by(id: current_shelter())
      @adoptions = Adoption.where(["shelter_id = ? and adopted = ?", @shelter.id, false])
    else
      @shelter = Shelter.find_by(id: params[:id])
      @adoption = Adoption.new()
    end
  end

  def index
    @shelters =Shelter.all
  end

  def edit
    if validate_shelter() && current_shelter().to_s() == params[:id]
      @shelter = Shelter.find(current_shelter())
    else
      redirect_to :root, alert: 'Please login, signup, or edit your own profile.'
    end
  end

  def update
    if validate_shelter() && current_shelter().to_s() == params[:id]
      @shelter = Shelter.find_by(id: current_shelter())

      if @shelter.update(shelter_params)
        redirect_to shelter_path(@shelter.id)
      else
        render :edit
      end
    else
      redirect_to :root, alert: 'Please login, signup, or edit your own profile.'
    end
  end



  private

  def shelter_params
    params.require(:shelter).permit(:name, :email, :home_state, :about_us, :password, :password_confirmation)
  end
end

app/helpers/shelters_helper.rb
module SheltersHelper
  def validate_shelter()
              current_shelter() != nil && Shelter.exists?(current_shelter()) ? true : false
  end


  def validate_shelter_adopt(email)
    !Shelter.find_by(email: email).nil? ? true : false
  end
end

app/views/shelters/_private.html.erb
<% if !@adoptions.empty? %>
  <h1>You have adoption(s) pending!</h1>

  <% @adoptions.each  do |adoption| %>

      <h2>Dog: <%= Dog.find_by(id: adoption.dog_id).name %></h2>
      <h2>Potential Owner: <%= Owner.find_by(id: adoption.owner_id).name %></h2>
      <%= link_to 'Confirm', {:controller => "adoptions", :action => 'move', :adoption => adoption.id } %>
  <% end %>
<% end %>
<h1>Here's your information</h1>
<% #ADD PHOTO %>
<h3>Name: <%= @shelter.name %></h3>
<h3>Email: <%= @shelter.email %></h3>
<h3>Home State: <%= @shelter.home_state %></h3>
<h3>Description: <%=  @shelter.about_us %></h3>
<h3>Dogs: </h3>
<br>
<div class="dog-box">
  <% @shelter.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h4><%= dog.name %>, <%= dog.age %></h4>
      <h4><%= dog.breed %></h4>
      <h4><a href=<%= edit_dog_path(dog.id) %>>Edit dog info</a></h4>
      <h4><%= button_to "Remove Dog", dog_path(dog.id), method: :delete %></h4>
    </div>
  <% end %>
</div>
<h2><a href=<%= new_dog_path %>>Add a Dog!</a></h2>
<h2><a href=<%= edit_shelter_path(@shelter.id) %>>Edit your info</a></h2>
<h2><%= link_to 'Remove Account', shelter_session_path(@shelter.id), method: :delete %></h2>

app/views/shelters/_public.html.erb
<h1>Here's the organization's information</h1>
<% #ADD PHOTO %>
<h2>Name: <%= @shelter.name %></h2>
<h2>Home State: <%= @shelter.home_state %></h2>
<h2>Description: <%=  @shelter.about_us %></h2>
<h2>Dogs: </h2>
<br>
<div class="dog-box">
  <% @shelter.dogs.each do |dog| %>
    <div class="dog-tile">
      <h3><%= dog.name %>, <%= dog.age %></h3>
      <h3><%= dog.breed %></h3>
      <%= link_to 'Adopt', {:controller => "adoptions", :action => 'create', :dog => dog.id } %>
    </div>
  <% end %>
</div>

app/views/shelters/edit.html.erb
<h1>Update your organization's information</h1>

<% if @shelter.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @shelter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @shelter, method: 'patch' do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Home State: <%= f.text_field :home_state %>
  Tell us about your organization: <%= f.text_area :about_us %>
  <%= f.submit "Update" %>
<% end %>

app/views/shelters/index.html.erb
<div class="yield-field">
  <h1>Here are our DogMa Shelters!</h1>
  <% @shelters.each do |shelter| %>
  <a href=<%= shelter_path(shelter) %>>
    <div class="shelter-tile">
      <h2>Name: <%= shelter.name %></h2>
      <h2>Home State: <%= shelter.home_state %></h2>
      <h2>Dogs Available: <%= shelter.dogs.count %></h2>
    </div>
  </a>
  <% end %>
</div>

app/views/shelters/new.html.erb
<h1>Enter your organization's information</h1>

<% if @shelter.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @shelter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @shelter, url: '/shelters' do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Home State: <%= f.text_field :home_state %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  Tell us about your organization: <%= f.text_area :about_us %>
  <%= f.submit "Create" %>
<% end %>

app/views/shelters/private_show.html.erb
<h1>Here's your information</h1>
<% #ADD PHOTO %>
<h3>Name: <%= @shelter.name %></h3>
<h3>Email: <%= @shelter.email %></h3>
<h3>Home State: <%= @shelter.home_state %></h3>
<h3>Dogs: </h3>
<br>
<div class="dog-box">
  <% @shelter.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h4><%= dog.name %>, <%= dog.age %></h4>
      <h4><%= dog.breed %></h4>
      <h4><a href=<%= edit_dog_path(dog.id) %>>Edit dog info</a></h4>
      <h4><%= button_to "Remove Dog", dog_path(dog.id), method: :delete %></h4>
    </div>
  <% end %>
</div>
<h2><a href=<%= new_dog_path %>>Add a Dog!</a></h2>
<h2><a href=<%= edit_shelter_path(@shelter.id) %>>Edit your info</a></h2>
<h2><%= link_to 'Remove Account', shelter_session_path(@shelter.id), method: :delete %></h2>

app/views/shelters/public_show.html.erb
<h1>Here's the organization's information</h1>
<% #ADD PHOTO %>
<h2>Name: <%= @shelter.name %></h2>
<h2>Home State: <%= @shelter.home_state %></h2>
<h2>Dogs: </h2>
<br>
<div class="dog-box">
  <% @shelter.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h3><%= dog.name %>, <%= dog.age %></h3>
      <h3><%= dog.breed %></h3>
      <%= form_with model: dog do |f| %>
        <%= f.hidden_field @shelter, @shelter.id %>
        <%= f.hidden_field dog, dog.id %>
        <%= f.button_to 'Adopt!', new_adoption_path %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shelters/show.html.erb
<% if current_shelter() == @shelter.id %>
<%= render 'private' %>
<% else %>
<%= render 'public' %>
<% end %>