config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs
  resources :owners
  resources :shelters
  resources :owner_sessions, only: [:new, :create, :destroy]
  resources :shelter_sessions, only: [:new, :create, :destroy]
  resource :adoptions, only: [:new, :create]

  get '/move', to: 'adoptions#move'
  get '/old-dogs', to: 'dogs#oldDogs'

  get '/auth/facebook/callback' => 'owner_sessions#create'
  root to: 'static#index'
end

app/controllers/shelter_sessions_controller.rb
class ShelterSessionsController < ApplicationController
  include ApplicationHelper
  include OwnersHelper
  include SheltersHelper
  def new
    @shelter = Shelter.new()
  end

  def create
      @shelter = Shelter.find_by(email: params[:shelter][:email])
      return head(:forbidden) unless @shelter.authenticate(params[:shelter][:password])
      session[:shelter_id] = @shelter.id
      redirect_to shelter_path(@shelter.id)
  end

  def destroy
    if validate_shelter() && current_shelter().to_s() == params[:id]
      session.delete(:shelter_id)
      redirect_to :root
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/views/shelter_sessions/new.html.erb
<h1>Shelter Login</h1>
<%= form_for @shelter, url: shelter_sessions_path  do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%=  f.password_field :password_confirmation %>
  <%= f.submit "Login" %>
<% end %>