config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs
  resources :owners
  resources :shelters
  resources :owner_sessions, only: [:new, :create, :destroy]
  resources :shelter_sessions, only: [:new, :create, :destroy]
  resource :adoptions, only: [:new, :create]

  get '/move', to: 'adoptions#move'
  get '/old-dogs', to: 'dogs#oldDogs'

  get '/auth/facebook/callback' => 'owner_sessions#create'
  root to: 'static#index'
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }, on: :create
  validates :email, presence: true, on: :update
  validates :password_digest, presence: true, allow_blank: true, if: :fb_logged?
  validates :about_me, :home_state, presence: true, allow_blank: true
  validates :uid, presence: true, allow_blank: true

  has_many :dogs
  has_many :adoptions
  has_many :shelters, through: :adoptions

  def fb_logged?
    uid != nil
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  include OwnersHelper
  include ApplicationHelper

  def new
    @owner = Owner.new()
  end

  def create
    if session[:shelter_id].nil? && session[:shelter_id].nil?
      @owner = Owner.new(owner_params)
      if @owner.valid?
        @owner.save
        redirect_to new_owner_session_path
      else
        render :new
      end
    else
      redirect_to dogs_path, alert: 'You must sign out before creating a new account.'
    end
  end

  def show
    if validate_owner() && current_owner().to_s == params[:id]
      @owner = Owner.find_by(id: current_owner())
    else
      @owner = Owner.find_by(id: params[:id])
    end
  end

  def index
    @owners =Owner.all
  end

  def edit

    if validate_owner() && current_owner().to_s == params[:id]
      @owner = Owner.find_by(id: current_owner())
    else
      redirect_to :root, alert: 'Please login, signup, or edit your own profile.'
    end
  end

  def update
    if validate_owner() && current_owner().to_s == params[:id]
      @owner = Owner.find_by(id: current_owner())
      if @owner.update(owner_params)
        redirect_to owner_path(@owner.id)
      else
        render :edit
      end
    else
      redirect_to :root, alert: 'Please login, signup, or edit your own profile.'
    end
  end

  def destroy
    if validate_owner() && Owner.find_by(id: curent_owner()) == params[:id]
      @owner = Owner.find(current_owner())
    else
      redirect_to :root, alert: 'Please login, signup, or edit your own profile.'
    end
  end

  private

  def owner_params
    params.require(:owner).permit(:name, :email, :home_state, :about_me, :password, :password_confirmation, :uid)
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
  def validate_owner
      current_owner() != nil && Owner.exists?(current_owner()) ? true : false
  end
end

app/views/owners/_private.html.erb
<h1>Here's your information</h1>
<% #ADD PHOTO %>
<h3>Name: <%= @owner.name %></h3>
<h3>Email: <%= @owner.email %></h3>
<h3>Home State: <%= @owner.home_state %></h3>
<h3>Description: <%=  @owner.about_me %></h3>
<h3>Dogs: </h3>
<br>
<div class="dog-box">
  <% @owner.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h4><%= dog.name %>, <%= dog.age %></h4>
      <h4><%= dog.breed %></h4>
      <%= link_to 'Edit dog info', edit_dog_path(dog.id) %>
      
      <%= button_to "Remove Dog", dog_path(dog.id), method: :delete %>
    </div>
  <% end %>
</div>
<h2><a href=<%= new_dog_path %>>Add a Dog!</a></h2>
<h4><%= link_to 'Edit your info', edit_owner_path(@owner.id) %></h4>
<h2><%= link_to 'Remove Account', owner_session_path(@owner.id), method: :delete %></h2>

app/views/owners/_public.html.erb
<h1>Here's their information</h1>
<% #ADD PHOTO %>
<h2>Name: <%= @owner.name %></h2>
<h2>Home State: <%= @owner.home_state %></h2>
<h2>Description: <%=  @owner.about_me %></h2>
<h2>Dogs: </h2>
<br>
<div class="dog-box">
  <% @owner.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h3><%= dog.name %>, <%= dog.age %></h3>
      <h3><%= dog.breed %></h3>
    </div>
  <% end %>
</div>

app/views/owners/edit.html.erb
<h1>Enter your updated information</h1>

<%= form_for @owner, url: owner_path(@owner.id), method: 'patch' do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Home State: <%= f.text_field :home_state %>
  Tell us about yourself: <%= f.text_area :about_me %>
  <% #ADD PROFILE PICTURE FIELD %>
  <% #? do you want your password to be able to be changed? %>
  <%= f.submit "Update" %>
<% end %>

app/views/owners/index.html.erb
<div class="yield-field">
<h1>Here are our DogMa Owners!</h1>
  <% @owners.each do |owner| %>
  <a href=<%= owner_path(owner) %>>
    <div class="shelter-tile">
      <h2>Name: <%= owner.name %></h2>
      <h2>Home State: <%= owner.home_state %></h2>
      <h2>Dogs: <%= owner.dogs.count %></h2>
    </div>
  </a>
  <% end %>
</div>

app/views/owners/new.html.erb
<h1>Enter your information</h1>

<%= form_for @owner do |f| %>
  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Home State: <%= f.text_field :home_state %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  Tell us about yourself: <%= f.text_area :about_me %>
  <% #ADD PROFILE PICTURE FIELD %>
  <%= f.submit "Create" %>
<% end %>

app/views/owners/private_show.html.erb
<h1>Here's your information</h1>
<% #ADD PHOTO %>
<h3>Name: <%= @owner.name %></h3>
<h3>Email: <%= @owner.email %></h3>
<h3>Home State: <%= @owner.home_state %></h3>
<h3>Dogs: </h3>
<br>
<div class="dog-box">
  <% @owner.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h4><%= dog.name %>, <%= dog.age %></h4>
      <h4><%= dog.breed %></h4>
      <h4><a href=<%= edit_dog_path(dog.id) %>>Edit dog info</a></h4>
      <%= form_with model: dog do |f| %>
        <%= f.hidden_field dog, dog.id %>
        <%= f.label 'Give me up: ' %>
        <%= f.button_to 'Rehome', abandon_path  %>
      <% end %>
      <h4><%= button_to "Remove Dog", { action: "delete", id: dog.id }, method: :delete, data: { confirm: "Are you sure?" }%></h4>
    </div>
  <% end %>
</div>

<h2><a href=<%= edit_owner_path(@owner.id) %>>Edit your info</a></h2>
<h2><%= button_to "Delete Account", { action: "delete", id: @owner.id }, method: :delete, data: { confirm: "Are you sure?" } %></h2>

app/views/owners/public_show.html.erb
<h1>Here's their information</h1>
<% #ADD PHOTO %>
<h2>Name: <%= @owner.name %></h2>
<h2>Home State: <%= @owner.home_state %></h2>
<h2>Dogs: </h2>
<br>
<div class="dog-box">
  <% @owner.dogs.each do |dog| %>
    <div class="dog-tile">
      <% #ADD PHOTO %>
      <h3><%= dog.name %>, <%= dog.age %></h3>
      <h3><%= dog.breed %></h3>
    </div>
  <% end %>
</div>

app/views/owners/show.html.erb
<% if current_owner == @owner.id %>
<%= render 'private' %>
<% else %>
<%= render 'public' %>
<% end %>