config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs
  resources :owners
  resources :shelters
  resources :owner_sessions, only: [:new, :create, :destroy]
  resources :shelter_sessions, only: [:new, :create, :destroy]
  resource :adoptions, only: [:new, :create]

  get '/move', to: 'adoptions#move'
  get '/old-dogs', to: 'dogs#oldDogs'

  get '/auth/facebook/callback' => 'owner_sessions#create'
  root to: 'static#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if validate_owner() %>
    <nav id='header-nav'>
      <%= image_tag ('dogma_logo.png'), class: 'nav-image' %>
      <h1 id='nav-title'>Dogma</h1>
      <ul id='nav-ul'>
        <li><a href=<%= owner_path(current_owner()) %>>Your Account</a></li>
        <li><a href=<%= owners_path %>>Owners</a></li>
        <li><a href=<%= dogs_path %>>Dogs</a></li>
        <li><a href=<%= shelters_path %>>Shelters</a></li>
      </ul>
      <% @owner =  Owner.find_by(id: current_owner())%>
      <%= button_to "logout", {:controller => :owner_sessions,
          :action => 'destroy', :id => @owner.id }, :method => :delete %>
    </nav>
    <% elsif validate_shelter() %>
    <nav id='header-nav'>
      <%= image_tag ('dogma_logo.png'), class: 'nav-image' %>
      <h1 id='nav-title'>Dogma</h1>
      <ul id='nav-ul'>
        <li><a href=<%= shelter_path(current_shelter()) %>>Your Account</a></li>
        <li><a href=<%= owners_path %>>Owners</a></li>
        <li><a href=<%= dogs_path %>>Dogs</a></li>
        <li><a href=<%= shelters_path %>>Shelters</a></li>
      </ul>
      <% @shelter =  Shelter.find_by(id: current_shelter())%>
      <%= button_to "logout", {:controller => :shelter_sessions,
          :action => 'destroy', :id => @shelter.id }, :method => :delete %>
    </nav>
    <% else %>
    <nav id='header-nav'>
      <%= image_tag ('dogma_logo.png'), class: 'nav-image' %>
      <h1 id='nav-title'>Dogma</h1>
      <ul id='nav-ul'>
        <li><a href="/">Login</a></li>
        <li><a href=<%= dogs_path %>>Dogs</a></li>
        <li><a href=<%= shelters_path %>>Shelters</a></li>
      </ul>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/owner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogMa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id='nav'>
      <ul id='nav-ul'>
        <li><a href=<%= owner_path(current_owner(session)) %>>Your Account</a></li>
        <li><a href=<%= owners_path %>>Owners</a></li>
        <li><a href=<%= dogs_path %>>Dogs</a></li>
        <li><a href=<%= shelters_path %>>Shelters</a></li>
        <li><a href=<%= owners_logout_path %>>Logout</a></li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/shelter.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogMa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id='nav'>
      <ul id='nav-ul'>
        <li><a href=<%= shelter_path(current_shelter(session)) %>>Your Account</a></li>
        <li><a href=<%= owners_path %>>Owners</a></li>
        <li><a href=<%= dogs_path %>>Dogs</a></li>
        <li><a href=<%= shelters_path %>>Shelters</a></li>
        <li><a href=<%= shelters_logout_path %>>Logout</a></li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>